services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    
  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rbouquet/data/wordpress'
  mariadb:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/rbouquet/data/mariadb'

networks:
  inception:
    driver: bridge
